name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy via Local Sync
        run: |
          # 因為 Runner 已經在你的伺服器內，直接進目錄同步即可
          cd /home/buddy/ricebookkeeping
          git fetch origin main
          git reset --hard origin/main
